#
# Prompt character
#

zmodload zsh/param/private

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

SPACESHIP_CHAR_DIVIDER="${SPACESHIP_CHAR_DIVIDER="$SPACESHIP_PROMPT_DEFAULT_DIVIDER"}"
SPACESHIP_CHAR_PREFIX="${SPACESHIP_CHAR_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"}"
SPACESHIP_CHAR_COLOR_SUCCESS="${SPACESHIP_CHAR_COLOR_SUCCESS="green"}"
SPACESHIP_CHAR_COLOR_FAILURE="${SPACESHIP_CHAR_COLOR_FAILURE="red"}"
SPACESHIP_CHAR_COLOR_ROOT_SUCCESS="${SPACESHIP_CHAR_COLOR_ROOT_SUCCESS="$SPACESHIP_CHAR_COLOR_SUCCESS"}"
SPACESHIP_CHAR_COLOR_ROOT_FAILURE="${SPACESHIP_CHAR_COLOR_ROOT_FAILURE="$SPACESHIP_CHAR_COLOR_FAILURE"}"
SPACESHIP_CHAR_SYMBOL="${SPACESHIP_CHAR_SYMBOL="➜"}"
SPACESHIP_CHAR_SYMBOL_ROOT="${SPACESHIP_CHAR_SYMBOL_ROOT="$SPACESHIP_CHAR_SYMBOL"}"
SPACESHIP_CHAR_SUFFIX="${SPACESHIP_CHAR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"

SPACESHIP_CHAR_PREFIX_SECONDARY="${SPACESHIP_CHAR_PREFIX_SECONDARY="$SPACESHIP_CHAR_PREFIX"}"
SPACESHIP_CHAR_COLOR_SECONDARY="${SPACESHIP_CHAR_COLOR_SECONDARY="yellow"}"
SPACESHIP_CHAR_COLOR_ROOT_SECONDARY="${SPACESHIP_CHAR_COLOR_ROOT_SECONDARY="$SPACESHIP_CHAR_COLOR_SECONDARY"}"
SPACESHIP_CHAR_SYMBOL_SECONDARY="${SPACESHIP_CHAR_SYMBOL_SECONDARY="$SPACESHIP_CHAR_SYMBOL"}"
SPACESHIP_CHAR_SYMBOL_ROOT_SECONDARY="${SPACESHIP_CHAR_SYMBOL_ROOT_SECONDARY="$SPACESHIP_CHAR_SYMBOL_SECONDARY"}"
SPACESHIP_CHAR_SUFFIX_SECONDARY="${SPACESHIP_CHAR_SUFFIX_SECONDARY="$SPACESHIP_CHAR_SUFFIX"}"

# ------------------------------------------------------------------------------
# Section
# ------------------------------------------------------------------------------

spaceship_char() {
  private color char

  if (( UID == 0 )); then
    char=$SPACESHIP_CHAR_SYMBOL_ROOT

    if (( RETVAL == 0 )); then
      color=$SPACESHIP_CHAR_COLOR_ROOT_SUCCESS
    else
      color=$SPACESHIP_CHAR_COLOR_ROOT_FAILURE
    fi
  else
    char=$SPACESHIP_CHAR_SYMBOL

    if (( RETVAL == 0 )); then
      color=$SPACESHIP_CHAR_COLOR_SUCCESS
    else
      color=$SPACESHIP_CHAR_COLOR_FAILURE
    fi
  fi

  spaceship::section \
    "$color" \
    "$SPACESHIP_CHAR_DIVIDER" \
    "$SPACESHIP_CHAR_PREFIX" \
    "$char" \
    "$SPACESHIP_CHAR_SUFFIX"
}
